// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using UploadFile.Data;

namespace UploadFile
{
    public partial class UploadfileContext : DbContext
    {
        public UploadfileContext()
        {
        }

        public UploadfileContext(DbContextOptions<UploadfileContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }

        public virtual DbSet<Exams> Exams { get; set; }
        public virtual DbSet<Finances> Finances { get; set; }

        public virtual DbSet<Attendances>Attendances { get; set; }

        public virtual DbSet<LectureMaterials> LectureMaterials { get; set; }

        public virtual DbSet<TimeTables> TimeTables { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Invoices>(entity =>
            {               

                entity.Property(e => e.Date).HasColumnType("datetime");
            });

            modelBuilder.Entity<Students>(entity =>
            {

                entity.Property(e => e.Date).HasColumnType("datetime");

            });


            modelBuilder.Entity<Employees>(entity =>
            {

                entity.Property(e => e.Date).HasColumnType("datetime");

               
            });

            modelBuilder.Entity<Exams>(entity =>
            {

                entity.Property(e => e.Date).HasColumnType("datetime");

            });

            modelBuilder.Entity<Finances>(entity =>
            {

                entity.Property(e => e.Date).HasColumnType("datetime");

            });

            modelBuilder.Entity<Attendances>(entity =>
            {

                entity.Property(e => e.Date).HasColumnType("datetime");

            });

            modelBuilder.Entity<LectureMaterials>(entity =>
            {

                entity.Property(e => e.Date).HasColumnType("datetime");

            });

            modelBuilder.Entity<TimeTables>(entity =>
            {

                entity.Property(e => e.Date).HasColumnType("datetime");

            });





            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}